// 8단계: 같은 전체에서 조각 크기를 맞춘 뒤 이름과 비교를 연결합니다.
(() => {
  const nav=document.querySelector('#units-steps'),host=document.querySelector('#units-content');
  const names=['조각의 크기부터','같은 칸 만들기','공통 단위 탐정','두 분수 실험실','모델과 분수식','다시 묶어 간단하게','나누기 ↔ 묶기','로봇의 오류 찾기','공통 단위 머신','보스 미션'];
  const states=names.map(()=>({}));let step=0;
  const el=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;};
  const add=(p,tag,text='',cls='')=>{const e=el(tag,text,cls);p.append(e);return e;};
  const btn=(p,text,fn)=>{const b=add(p,'button',text);b.type='button';b.onclick=fn;return b;};
  const msg=p=>{const m=add(p,'p','','unit-feedback');m.setAttribute('role','status');return m;};
  function frac(p,n,d){const f=add(p,'span','','reading-fraction');f.setAttribute('role','img');f.setAttribute('aria-label',`${d}분의 ${n}`);add(f,'span',String(n),'reading-top');add(f,'span',String(d),'reading-bottom');return f;}
  function eq(p,a,b,sign='='){const row=add(p,'div','','unit-equation');frac(row,...a);add(row,'span',sign);frac(row,...b);}
  function bar(p,v,label,touch){const row=add(p,'div','','unit-row'),head=add(row,'div','','unit-row-title');add(head,'strong',label);frac(head,...v);const track=add(row,'div','','unit-bar');track.setAttribute('aria-label',label+' 막대');track.setAttribute('role','group');const fill=add(track,'div','','unit-fill');fill.style.width=(v[0]/v[1]*100)+'%';const cells=add(track,'div','','unit-cells');cells.style.gridTemplateColumns=`repeat(${v[1]},minmax(0,1fr))`;for(let i=0;i<v[1];i++){const cell=add(cells,touch?'button':'span','','unit-cell');if(touch){cell.type='button';cell.setAttribute('aria-label',`${label} ${i+1}번째 조각`);cell.onclick=()=>touch(cell);}}return row;}
  const valid=(pair,d)=>Number.isInteger(d)&&d>=2&&d<=60&&pair.every(v=>d%v[1]===0);
  const convert=(v,d)=>[v[0]*(d/v[1]),d];
  function pairBars(p,pair){pair.forEach((v,i)=>bar(p,v,i?'분수 B':'분수 A'));}
  function compare(p,base,pair,s){add(p,'p','같은 크기의 조각이 되었어요. 색칠된 조각 수를 비교해 보세요.');const actions=add(p,'div','','unit-actions'),m=msg(p);for(const [label,sign]of[['A가 크다','>'],['B가 크다','<'],['같다','=']])btn(actions,label,()=>{const correct=pair[0][0]===pair[1][0]?'=':pair[0][0]>pair[1][0]?'>':'<';if(sign!==correct){m.textContent='조각 한 칸의 크기가 같아요. 색칠된 칸 수를 다시 살펴보세요.';return;}s.solved=true;m.replaceChildren();add(m,'span','같은 크기의 조각 수로 비교했어요!');eq(m,...pair,sign);eq(m,...base,sign);s.onSolved?.();});}
  function chooser(p,base,s,options,{comparison=false,hiddenModel=false,onSuccess}={}){if(!hiddenModel||s.d)pairBars(p,s.d?base.map(v=>convert(v,s.d)):base);const actions=add(p,'div','','unit-actions'),m=msg(p);function choose(d){if(!valid(base,d)){m.textContent='그 칸 수로는 두 막대의 원래 조각을 모두 똑같이 다시 나눌 수 없어요. 다른 칸 수를 찾아보세요.';return;}s.d=d;s.solved=false;s.compared=false;s.explained=false;render();}if(options){for(const d of options)btn(actions,`${d}칸`,()=>choose(d));}else{const input=add(actions,'input');input.type='number';input.min=2;input.max=60;input.setAttribute('aria-label','공통 칸 수');const form=add(p,'form');form.append(actions);const submit=add(form,'button','모델로 검증');submit.type='submit';form.onsubmit=e=>{e.preventDefault();choose(Number(input.value));};}if(s.d){base.forEach(v=>eq(p,v,convert(v,s.d)));add(p,'p',`두 막대의 한 칸은 모두 ${s.d}분의 1이에요.`,'unit-success');if(comparison){s.onSolved=onSuccess;compare(p,base,base.map(v=>convert(v,s.d)),s);}else onSuccess?.();}}
  function splitModel(p,base,s,{name=false,onSuccess}={}){s.values??=base.map(v=>[...v]);const layout=add(p,'div','','unit-model-layout'),models=add(layout,'div'),expressions=add(layout,'div','','unit-expressions');s.values.forEach((v,i)=>{bar(models,v,i?'분수 B':'분수 A');const controls=add(models,'div','','unit-actions');for(const k of [2,3])btn(controls,`${i?'B':'A'}의 각 칸을 ${k}개로 나누기`,()=>{if(v[1]*k>60){notice.textContent='60칸까지 탐구해요. 처음으로 돌아가 다시 나눠 보세요.';return;}s.values[i]=[v[0]*k,v[1]*k];s.solved=false;s.named=false;render();});eq(expressions,base[i],v,'→');});const notice=msg(p);btn(p,'처음 막대로',()=>{s.values=base.map(v=>[...v]);s.named=false;s.solved=false;render();});if(s.values[0][1]===s.values[1][1]){add(p,'p',`🎉 두 분수의 조각 크기가 같아졌어요! 한 칸은 ${s.values[0][1]}분의 1이에요.`,'unit-success');expressions.classList.add('common-found');if(name){btn(p,'분모가 같아졌어요',()=>{s.named=true;render();});if(s.named)add(p,'p','이처럼 같은 전체에서 두 분수의 조각 크기를 같게 나타내는 것을 통분이라고 해요.','unit-success');}onSuccess?.();}}
  function grouping(p,start,s,{boss=false}={}){s.value??=[...start];bar(p,s.value,'현재 분수');const actions=add(p,'div','','unit-actions'),m=msg(p);for(const k of [2,3])btn(actions,`${k}칸씩 묶기`,()=>{const[n,d]=s.value;if(n%k||d%k||d/k<2){m.textContent='색칠 경계와 전체를 모두 맞춰 묶을 수 있는 수를 찾아보세요.';return;}s.value=[n/k,d/k];s.changed=true;render();});if(s.changed){eq(p,start,s.value);add(p,'p','크기는 그대로인데 조각 수가 줄었어요. 이것을 약분이라고 해요.','unit-success');if(boss){btn(p,'더 묶을 수 없어요',()=>{const[n,d]=s.value;let divisor=false;for(let k=2;k<=Math.min(n,d);k++)if(n%k===0&&d%k===0)divisor=true;if(divisor)m.textContent='같은 수만큼 더 묶을 수 있는지 살펴보세요.';else{s.solved=true;render();}});}}}
  function render(){host.replaceChildren();nav.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===step)));add(host,'h2',`8-${step+1} ${names[step]}`);const s=states[step];
    if(step===0){add(host,'p','전체 길이는 같아요. 어느 분수가 더 클까요?');const pair=[[1,2],[1,3]];pair.forEach((v,i)=>bar(host,v,i?'분수 B':'분수 A',()=>{s.touched??=new Set();s.touched.add(i);s.last=i;render();}));const a=add(host,'div','','unit-actions'),m=msg(host);for(const [label,ok]of[['A가 크다',true],['B가 크다',false],['같다',false]])btn(a,label,()=>{if(ok){s.compared=true;render();}else m.textContent='전체의 왼쪽 끝을 맞추고 색칠된 길이를 살펴보세요.';});if(s.compared)add(host,'p','A의 색칠된 길이가 더 길어요. 그런데 두 막대의 한 칸 크기는 같을까요? 각 막대의 칸을 눌러 보세요.');if(s.last!==undefined){const p=add(host,'div','','unit-equation');add(p,'span',s.last?'B의 한 칸':'A의 한 칸');frac(p,1,pair[s.last][1]);}if(s.touched?.size===2)add(host,'p','조각의 크기가 달라요. 같은 전체라도 나눈 수가 다르면 한 칸의 크기가 달라져요.','unit-success');}
    if(step===1){add(host,'p','한 칸을 몇 개씩 더 나누면 두 막대의 작은 조각이 같아질까요? 직접 선택해 보세요.');splitModel(host,[[1,2],[1,3]],s);}
    if(step===2){add(host,'p','이분의 일과 사분의 일을 같은 크기의 칸으로 나타내 보세요.');s.found??=new Set();chooser(host,[[1,2],[1,4]],s,[4,6,8],{onSuccess:()=>s.found.add(s.d)});add(host,'p',`발견한 공통 칸: ${[...s.found].join(', ')||'아직 없어요'}`);if(s.found.has(4)&&s.found.has(8)){add(host,'p','둘 다 가능해요. 더 적은 조각으로 간단하게 나타내려면?');const m=msg(host);for(const d of [4,8])btn(host,`${d}등분이 더 간단해요`,()=>{m.textContent=d===4?'맞아요! 가능한 공통 칸 중 적은 수를 쓰면 비교하기 편리해요.':'8등분도 가능해요. 어느 쪽의 조각 수가 더 적은지 살펴보세요.';});}}
    if(step===3){s.which??=0;const a=add(host,'div','','unit-actions');btn(a,'이분의 일과 삼분의 이',()=>{s.which=0;s.d=null;render();});btn(a,'사분의 삼과 삼분의 이',()=>{s.which=1;s.d=null;render();});chooser(host,s.which?[[3,4],[2,3]]:[[1,2],[2,3]],s,[6,12,24],{comparison:true});}
    if(step===4){add(host,'p','왼쪽 막대를 바꾸면 오른쪽 분수식도 함께 바뀌어요. 같은 크기의 조각을 만들어 보세요.');splitModel(host,[[1,2],[1,3]],s,{name:true});}
    if(step===5){add(host,'p','같은 크기의 작은 조각끼리 묶어 더 간단하게 나타내 볼까요?');grouping(host,[6,8],s);}
    if(step===6){s.value??=[1,2];bar(host,s.value,'같은 양');const m=msg(host);btn(host,'✂️ 각 칸을 3개로 나누기',()=>{if(s.value[1]*3>54){m.textContent='다시 묶어 되돌아가 보세요.';return;}s.value=s.value.map(n=>n*3);s.changed=true;render();});btn(host,'🧩 3칸씩 다시 묶기',()=>{if(s.value.some(n=>n%3)||s.value[1]/3<2){m.textContent='먼저 잘게 나눈 뒤 묶어 보세요.';return;}s.value=s.value.map(n=>n/3);s.changed=true;render();});if(s.changed){eq(host,[1,2],s.value);add(host,'p','잘게 나누기는 다른 분수와 조각 크기를 맞추는 데 쓸 수 있어요. 다시 묶기는 같은 양을 더 간단하게 나타내요.');}}
    if(step===7){add(host,'p','🤖 이분의 일은 사분의 이, 삼분의 일은 육분의 이! 분자가 둘 다 2니까 같아!');eq(host,[1,2],[2,4]);eq(host,[1,3],[2,6]);btn(host,'오류 찾기 · 막대 보기',()=>{s.shown=true;render();});if(s.shown){pairBars(host,[[2,4],[2,6]]);add(host,'p','무엇이 문제일까요?');const m=msg(host);for(const [text,ok]of[['조각의 크기가 아직 달라요',true],['색칠한 칸 수가 같아서 무조건 같아요',false],['색깔이 달라요',false]])btn(host,text,()=>{if(ok){s.reason=true;render();}else m.textContent='한 칸의 크기를 비교해 보세요.';});if(s.reason){add(host,'p','원래 두 분수를 같은 크기의 칸으로 다시 나타내 고쳐 보세요.');chooser(host,[[1,2],[1,3]],s,[4,6,12],{comparison:true});}}}
    if(step===8){add(host,'p','삼분의 이와 사분의 삼을 모두 나타낼 수 있는 공통 칸을 찾아보세요.');chooser(host,[[2,3],[3,4]],s,[6,8,12,16],{comparison:true});}
    if(step===9)boss(s);
    const foot=add(host,'div','','reading-footer');if(step)btn(foot,'← 이전 활동',()=>{step--;render();});if(step<9)btn(foot,'다음 활동 →',()=>{step++;render();});
  }
  function boss(s){s.round??=0;s.tasks??=Array.from({length:5},()=>({}));if(s.round===5){add(host,'p','🏆 공통 단위 탐구 완료! 같은 전체에서 조각 크기를 맞추면 색칠된 조각 수로 비교할 수 있어요.','unit-success');btn(host,'보스 미션 다시 하기',()=>{s.round=0;s.tasks=null;render();});return;}const t=s.tasks[s.round];add(host,'h3',`미션 ${s.round+1}`);const done=()=>{t.solved=true;const next=host.querySelector('.unit-next');if(next)next.hidden=false;};if(s.round===0)splitModel(host,[[1,2],[1,3]],t,{onSuccess:done});if(s.round===1)chooser(host,[[2,3],[3,4]],t,[6,8,12,16],{onSuccess:done});if(s.round===2){add(host,'p','오분의 삼과 삼분의 이: 먼저 공통 칸 수를 생각하고, 모델로 검증하세요.');if(!t.d){eq(host,[3,5],[2,3],'와');}chooser(host,[[3,5],[2,3]],t,null,{hiddenModel:true,onSuccess:done});}if(s.round===3)grouping(host,[4,6],t,{boss:true});if(s.round===4){add(host,'p','사분의 삼과 육분의 오를 같은 칸으로 만든 뒤 비교하고 이유를 설명하세요.');chooser(host,[[3,4],[5,6]],t,[8,12,24],{comparison:true,onSuccess:()=>{t.compared=true;reason.hidden=false;}});const reason=add(host,'div');reason.hidden=!t.compared;add(reason,'p','왜 비교할 수 있나요?');const m=msg(reason);btn(reason,'한 칸의 크기가 같아져서 색칠한 조각 수를 비교할 수 있어요',()=>{t.explained=true;done();});btn(reason,'분모가 커지면 언제나 분수도 커져요',()=>{m.textContent='전체와 색칠된 길이는 그대로예요. 한 칸의 크기와 개수를 생각해 보세요.';});}const next=btn(host,s.round===4?'탐구 완료':'다음 미션',()=>{s.round++;render();});next.className='unit-next';next.hidden=s.round===4?!t.explained:!t.solved;}
  names.forEach((name,i)=>{const b=btn(nav,`8-${i+1}`,()=>{step=i;render();});b.title=name;});render();
})();


